# Generated by Django 5.2.6 on 2025-09-19 00:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('person_id', models.CharField(max_length=100)),
                ('problem_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.TextField()),
                ('problem_type', models.CharField(choices=[('pothole', 'Pothole'), ('streetlight', 'Street Light'), ('water', 'Water Supply'), ('garbage', 'Garbage Collection'), ('traffic', 'Traffic Signal'), ('other', 'Other')], max_length=20)),
                ('urgency_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20)),
            ],
            options={
                'db_table': 'civic_issues',
                'ordering': ['-datetime'],
            },
        ),
    ]
