name: departmentselection
description: A Flutter app for civic complaint department selection

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  camera: ^0.10.5
  geolocator: ^10.1.0
  geocoding: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
