name: departmentselection
description: A Flutter app for civic complaint department selection

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Firebase plugins (let Flutter resolve versions automatically)
  firebase_core:
  cloud_firestore:
  firebase_auth:
  firebase_storage:

  camera: ^0.10.5
  geolocator: ^10.0.0
  geocoding: ^2.1.1
  path_provider:        # <-- for file/directory access

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
